In [98]:
import numpy as np
import torch

In [99]:
inputs=np.array([[73, 67, 43],
                 [91, 88, 64],
                 [87, 134, 58],
                 [102, 43, 37],
                 [69, 96, 70]], dtype='float32')

In [100]:
targets=np.array([[56, 70],
                 [81, 101],
                 [119,133],
                 [22, 37],
                 [103, 119]], dtype='float32')

In [101]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [102]:
w=torch.randn(2, 3, requires_grad=True)
b=torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.7758, -0.2629,  1.3045],
        [-0.5475,  0.1565,  1.1041]], requires_grad=True)
tensor([-1.0687, -0.4218], requires_grad=True)


In [103]:
def model(x):
    return x @ w.t() + b

In [104]:
preds = model(inputs)
print(preds)

tensor([[-19.2213,  17.5755],
        [-11.3114,  34.1943],
        [-28.1288,  36.9602],
        [-43.2368,  -8.6839],
        [ 11.4800,  54.1165]], grad_fn=<AddBackward0>)


In [105]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [106]:
#MSE loss
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff) / diff.numel()


In [107]:
loss=mse(preds, targets)
print(loss)
#the lower the loss the better the model

tensor(7119.0146, grad_fn=<DivBackward0>)


In [108]:
loss.backward()

In [109]:
print(w)
print(w.grad)

tensor([[-0.7758, -0.2629,  1.3045],
        [-0.5475,  0.1565,  1.1041]], requires_grad=True)
tensor([[-7932.1455, -8893.9189, -5299.2153],
        [-5479.7007, -6090.7822, -3666.4565]])


In [110]:
print(b)
print(b.grad)

tensor([-1.0687, -0.4218], requires_grad=True)
tensor([-94.2836, -65.1675])


In [129]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [130]:
print(w)
print(b)

tensor([[-0.2205,  0.3597,  1.6755],
        [-0.1639,  0.5829,  1.3608]], requires_grad=True)
tensor([-1.0621, -0.4173], requires_grad=True)


In [131]:
preds= model(inputs)
loss=mse(preds, targets)
print(loss)

tensor(566.8644, grad_fn=<DivBackward0>)
