In [98]:
import numpy as np
import torch

In [99]:
inputs=np.array([[73, 67, 43],
                 [91, 88, 64],
                 [87, 134, 58],
                 [102, 43, 37],
                 [69, 96, 70]], dtype='float32')

In [100]:
targets=np.array([[56, 70],
                 [81, 101],
                 [119,133],
                 [22, 37],
                 [103, 119]], dtype='float32')

In [101]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [102]:
w=torch.randn(2, 3, requires_grad=True)
b=torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.7758, -0.2629,  1.3045],
        [-0.5475,  0.1565,  1.1041]], requires_grad=True)
tensor([-1.0687, -0.4218], requires_grad=True)


In [103]:
def model(x):
    return x @ w.t() + b

In [104]:
preds = model(inputs)
print(preds)

tensor([[-19.2213,  17.5755],
        [-11.3114,  34.1943],
        [-28.1288,  36.9602],
        [-43.2368,  -8.6839],
        [ 11.4800,  54.1165]], grad_fn=<AddBackward0>)


In [105]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [106]:
#MSE loss
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff) / diff.numel()


In [107]:
loss=mse(preds, targets)
print(loss)
#the lower the loss the better the model

tensor(7119.0146, grad_fn=<DivBackward0>)


In [108]:
loss.backward()

In [109]:
print(w)
print(w.grad)

tensor([[-0.7758, -0.2629,  1.3045],
        [-0.5475,  0.1565,  1.1041]], requires_grad=True)
tensor([[-7932.1455, -8893.9189, -5299.2153],
        [-5479.7007, -6090.7822, -3666.4565]])


In [110]:
print(b)
print(b.grad)

tensor([-1.0687, -0.4218], requires_grad=True)
tensor([-94.2836, -65.1675])


In [129]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [130]:
print(w)
print(b)

tensor([[-0.2205,  0.3597,  1.6755],
        [-0.1639,  0.5829,  1.3608]], requires_grad=True)
tensor([-1.0621, -0.4173], requires_grad=True)


In [131]:
preds= model(inputs)
loss=mse(preds, targets)
print(loss)

tensor(566.8644, grad_fn=<DivBackward0>)


In [132]:
print(preds)

tensor([[ 78.9817,  85.1831],
        [117.7500, 123.0495],
        [125.1243, 142.3535],
        [ 53.9010,  58.2751],
        [135.5321, 139.4837]], grad_fn=<AddBackward0>)


In [133]:
import torch.nn as nn

In [134]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [135]:
from torch.utils.data import TensorDataset

In [139]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [140]:
from torch.utils.data import DataLoader

In [141]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)


In [142]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [119., 133.],
        [ 81., 101.],
        [ 22.,  37.],
        [103., 119.]])


In [143]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3539,  0.3489, -0.4646],
        [ 0.2363, -0.3310, -0.2721]], requires_grad=True)
Parameter containing:
tensor([-0.5606, -0.1254], requires_grad=True)


In [144]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3539,  0.3489, -0.4646],
         [ 0.2363, -0.3310, -0.2721]], requires_grad=True),
 Parameter containing:
 tensor([-0.5606, -0.1254], requires_grad=True)]

In [145]:
preds=model(inputs)
preds

tensor([[-22.9942, -16.7525],
        [-31.7928, -25.1640],
        [-11.5381, -39.7039],
        [-38.8455,  -0.3224],
        [-24.0021, -34.6435],
        [-22.9942, -16.7525],
        [-31.7928, -25.1640],
        [-11.5381, -39.7039],
        [-38.8455,  -0.3224],
        [-24.0021, -34.6435],
        [-22.9942, -16.7525],
        [-31.7928, -25.1640],
        [-11.5381, -39.7039],
        [-38.8455,  -0.3224],
        [-24.0021, -34.6435]], grad_fn=<AddmmBackward>)

In [146]:
import torch.nn.functional as F
loss_fn=F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(13410.3486, grad_fn=<MseLossBackward>)


In [147]:
opt=torch.optim.SGD(model.parameters(), lr=1e-5)

In [148]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [151]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 43.4433
Epoch [20/100], Loss: 61.9642
Epoch [30/100], Loss: 18.8043
Epoch [40/100], Loss: 31.1204
Epoch [50/100], Loss: 28.6206
Epoch [60/100], Loss: 8.5500
Epoch [70/100], Loss: 38.5983
Epoch [80/100], Loss: 23.1404
Epoch [90/100], Loss: 20.4865
Epoch [100/100], Loss: 42.5839


In [152]:
preds= model(inputs)
preds

tensor([[ 57.8426,  71.1422],
        [ 79.3148,  98.1757],
        [125.9416, 139.0132],
        [ 23.8238,  40.3043],
        [ 95.0515, 112.7297],
        [ 57.8426,  71.1422],
        [ 79.3148,  98.1757],
        [125.9416, 139.0132],
        [ 23.8238,  40.3043],
        [ 95.0515, 112.7297],
        [ 57.8426,  71.1422],
        [ 79.3148,  98.1757],
        [125.9416, 139.0132],
        [ 23.8238,  40.3043],
        [ 95.0515, 112.7297]], grad_fn=<AddmmBackward>)

In [153]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])