In [1]:
import numpy as np
import torch

In [2]:
# temp, rainfall, humidity
inputs=np.array([[73, 67, 43],
                 [91, 88, 64],
                 [87, 134, 58],
                 [102, 43, 37],
                 [69, 96, 70]], dtype='float32')

In [3]:
#apples, oranges
targets=np.array([[56, 70],
                 [81, 101],
                 [119,133],
                 [22, 37],
                 [103, 119]], dtype='float32')

In [4]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [18]:
w=torch.randn(2, 3, requires_grad=True)
b=torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.4887,  0.8227,  0.7707],
        [ 0.0122, -0.1675, -2.2005]], requires_grad=True)
tensor([-1.3474,  0.4701], requires_grad=True)


In [19]:
def model(x):
    return x @ w.t() + b

In [20]:
preds = model(inputs)
print(preds)

tensor([[  51.2405, -104.4839],
        [  75.9056, -153.9928],
        [ 111.0829, -148.5431],
        [  12.6982,  -86.9066],
        [  97.8630, -168.8047]], grad_fn=<AddBackward0>)


In [17]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
