In [1]:
import numpy as np
import torch

In [2]:
# temp, rainfall, humidity
inputs=np.array([[73, 67, 43],
                 [91, 88, 64],
                 [87, 134, 58],
                 [102, 43, 37],
                 [69, 96, 70]], dtype='float32')

In [3]:
#apples, oranges
targets=np.array([[56, 70],
                 [81, 101],
                 [119,133],
                 [22, 37],
                 [103, 119]], dtype='float32')

In [4]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [24]:
w=torch.randn(2, 3, requires_grad=True)
b=torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-1.3166, -1.6427, -0.4880],
        [ 0.0209,  0.3109, -1.1837]], requires_grad=True)
tensor([ 0.9554, -0.4513], requires_grad=True)


In [25]:
def model(x):
    return x @ w.t() + b

In [26]:
preds = model(inputs)
print(preds)

tensor([[-226.2002,  -28.9926],
        [-294.6433,  -46.9450],
        [-362.0146,  -25.6229],
        [-222.0277,  -28.7463],
        [-281.7483,  -52.0200]], grad_fn=<AddBackward0>)


In [27]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [33]:
#mean squared error to improve our model
diff = preds-targets
diff_sqr=diff*diff

torch.sum(diff_sqr)/diff.numel()

tensor(75011.9531, grad_fn=<DivBackward0>)

In [36]:
#MSE loss
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff) / diff.numel()


In [39]:
#compute loss
loss=mse(preds, targets)
print(loss)
#the lower the loss the better the model

tensor(75011.9531, grad_fn=<DivBackward0>)


In [40]:
loss.backward()

In [41]:
#gradients for weight
print(w)
print(w.grad)

tensor([[-1.3166, -1.6427, -0.4880],
        [ 0.0209,  0.3109, -1.1837]], requires_grad=True)
tensor([[-29614.1777, -32769.8047, -20007.2070],
        [-10599.2324, -12030.4307,  -7465.8618]])


In [42]:
#gradients for bias
print(b)
print(b.grad)

tensor([ 0.9554, -0.4513], requires_grad=True)
tensor([-353.5268, -128.4654])


In [43]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])
